### ISSUE TITLE
Does not work with the US version of the game

### ISSUE THREAD

**Issue by Grunerd** [SuiMachine/Starship-Troopers-FOV-Changer#1]
I know it's been 3 years and you probably have no interest in ever revisiting Starship Troopers from 2005 again, but I'm having trouble find the right addresses to apply this FOV fix to the US-.exe (0.524) of the game. Your tool only shows that it's the wrong file version andrefers to WSGF. :/

Maybe you can help?

**Comment by SuiMachine** [comment]
No idea. Been a while since I've made it. Will try and have a look at it this week.

**Comment by SuiMachine** [comment]
I've replaced it with simple pattern scan method - hopefully it helps, if not - will probably need an access to US exe (unless it's wrapped in some copy protection method... then I guess will have to re-write entire thing as a wrapper DLL).

https://github.com/SuiMachine/Starship-Troopers-FOV-Changer/releases/tag/1.2

**Comment by Grunerd** [comment]
Thank you so, so much. This works like a charm! :)
